/* Populated by react-webpack-redux:action */
export const SELECT_MATERIAL = 'SELECT_MATERIAL'

export const SELECT_SURFACE_COLOUR = 'SELECT_SURFACE_COLOUR'
export const SURFACE_COLOURS_FETCH_REQUESTED = 'SURFACE_COLOURS_FETCH_REQUESTED'
export const SURFACE_COLOURS_FETCH_SUCCEEDED = 'SURFACE_COLOURS_FETCH_SUCCEEDED'

export const SELECT_EDGE_COLOUR = 'SELECT_EDGE_COLOUR'
export const EDGE_COLOURS_FETCH_REQUESTED = 'EDGE_COLOURS_FETCH_REQUESTED'
export const EDGE_COLOURS_FETCH_SUCCEEDED = 'EDGE_COLOURS_FETCH_SUCCEEDED'
